# Generated by Django 3.2.3 on 2022-03-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
