# Generated by Django 3.2.3 on 2022-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
