# Generated by Django 3.2.3 on 2022-11-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_auto_20221104_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isStaff',
        ),
    ]
